version: 2.1

jobs:
  test:
    docker:
      - image: cimg/ruby:2.6.1
    steps:
      - checkout
      - run: bin/setup
      - run: rake spec
      - run:
          command: bundle exec rspec --format RspecJunitFormatter -o ~/rspec/rspec.xml
          when: always
      - store_test_results:
          path: ~/rspec

workflows:
  version: 2
  test:
    jobs:
      - test
