version: 2.1

jobs:
  test:
    docker:
      - image: cimg/ruby:2.6.1
    steps:
      - checkout
      - run: bin/setup
      - run: rake spec

workflows:
  version: 2
  test:
    jobs:
      - test
